# app/tests/db/test_db_connection.py

import pytest
from sqlalchemy.exc import OperationalError
from app.db.session import get_db

def test_db_connection():
    try:
        # Intenta abrir y cerrar una sesi贸n con la base de datos
        with get_db() as _:
            pass
    except OperationalError as e:
        pytest.fail(f"La conexi贸n a la base de datos fall贸: {str(e)}")
    except Exception as e:
        pytest.fail(f"Ocurri贸 un error inesperado: {str(e)}")